In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import re

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [2]:
df = pd.read_csv("amazonreviews.tsv", sep="\t")

In [3]:
df.head()

  label                                             review
0   pos  Stuning even for the non-gamer: This sound tra...
1   pos  The best soundtrack ever to anything.: I'm rea...
2   pos  Amazing!: This soundtrack is my favorite music...
3   pos  Excellent Soundtrack: I truly like this soundt...
4   pos  Remember, Pull Your Jaw Off The Floor After He...

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   label   10000 non-null  object
 1   review  10000 non-null  object
dtypes: object(2)
memory usage: 156.4+ KB

In [5]:
df.isnull().sum()

label     0
review    0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df["label"] = df["label"].map({"pos": 1, "neg": 0})

df.head()

   label                                             review
0      1  Stuning even for the non-gamer: This sound tra...
1      1  The best soundtrack ever to anything.: I'm rea...
2      1  Amazing!: This soundtrack is my favorite music...
3      1  Excellent Soundtrack: I truly like this soundt...
4      1  Remember, Pull Your Jaw Off The Floor After He...

In [8]:
import re
import nltk

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [9]:
stemmer = PorterStemmer()
stop_words = set(stopwords.words("english"))

In [10]:
def preprocess(text):

    text = text.lower()

    text = re.sub(r'[^a-zA-Z]', ' ', text)

    words = text.split()

    words = [stemmer.stem(word) for word in words if word not in stop_words]

    return " ".join(words)

In [11]:
df["clean_review"] = df["review"].apply(preprocess)

In [12]:
df[["review", "clean_review"]].head()

,review,clean_review
0,Stuning even for the non-gamer: This sound tra...,stune even non gamer sound track beauti paint ...
1,The best soundtrack ever to anything.: I'm rea...,best soundtrack ever anyth read lot review say...
2,Amazing!: This soundtrack is my favorite music...,amaz soundtrack favorit music time hand intens...
3,Excellent Soundtrack: I truly like this soundt...,excel soundtrack truli like soundtrack enjoy v...
4,"Remember, Pull Your Jaw Off The Floor After He...",rememb pull jaw floor hear play game know divi...

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=5000)

X = tfidf.fit_transform(df["clean_review"]).toarray()

y = df["label"]

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(8000, 5000)
(2000, 5000)

In [15]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train, y_train)

LogisticRegression()

In [16]:
y_pred = model.predict(X_test)

print(y_pred[:10])

[0 0 0 0 1 1 1 0 1 0]

In [17]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.853

In [18]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[890 147]
 [147 816]]

In [19]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.86      0.86      0.86      1037
           1       0.85      0.85      0.85       963

    accuracy                           0.85      2000
   macro avg       0.85      0.85      0.85      2000
weighted avg       0.85      0.85      0.85      2000

In [20]:
print("Conclusion")
print("1. The Amazon review dataset was successfully preprocessed.")
print("2. Text data was converted into numerical features using TF-IDF.")
print("3. Logistic Regression was trained for sentiment classification.")
print("4. The model successfully classified reviews as Positive or Negative.")
print("5. Accuracy, Confusion Matrix and Classification Report were used for evaluation.")
print("6. The model can be used for automated sentiment analysis of customer reviews.")

Conclusion
1. The Amazon review dataset was successfully preprocessed.
2. Text data was converted into numerical features using TF-IDF.
3. Logistic Regression was trained for sentiment classification.
4. The model successfully classified reviews as Positive or Negative.
5. Accuracy, Confusion Matrix and Classification Report were used for evaluation.
6. The model can be used for automated sentiment analysis of customer reviews.